const types = {
  ADD_SHOE: "ADD_SHOE",
  REMOVE_SHOE: "REMOVE_SHOE",
  UPDATE_QUANTITY: "CHANGE_QUANTITY",
  UPDATE_SIZE: "UPDATE_SIZE",
  SELECT_SHOE: "SELECT_SHOE",
  SELECT_SHOE_SIZE: "SELECT_SHOE_SIZE",
};

export default types;
