const types = {
  ADD_SHOE: "ADD_SHOE",
  REMOVE_SHOE: "REMOVE_SHOE",
  UPDATE_QUANTITY: "CHANGE_QUANTITY",
  UPDATE_SIZE: "UPDATE_SIZE",
  SELECT_SHOE: "SELECT_SHOE",
  SELECT_SHOE_SIZE: "SELECT_SHOE_SIZE",
  OPEN_SHOE_MODAL: "OPEN_SHOE_MODAL",
  CLOSE_SHOE_MODAL: "CLOSE_SHOE_MODAL",
  ADD_RECENT: "ADD_RECENT",
  REMOVE_RECENT: "REMOVE_RECENT",
};

export default types;
